name: Resolviendo el coso de Git 2 jeej

on:
  push:
    branches:
      - main

jobs:
  solve:
    runs-on: ubuntu-latest

    steps:
      - name: Hacer solicitdud a la pagina esa fea cochina q no me deja entrar malditasea
        run: |
          response=$(curl -s -H "Content-Type: application/json" -X GET "https://actions.ctf.cert.unlp.edu.ar")
          echo "Respuesta del servidor feo ese:"
          echo "$response"
